spring:
  application:
    name: MMCS Nexus

  datasource:
    url: jdbc:postgresql://localhost:1096/mmcsnexus
    username: postgres
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          